steps:
  init:
    - echo secret_v1 > secret.txt
  docker_build:
    image: pcit/docker
    with:
      # registry: docker.khs1994.com
      repo: pcit/alpine
      # target: php
      build_args:
        - a=1
        - b=2
      context: ./tests
      dockerfile: tests/Dockerfile.secret
      username: ${DOCKER_USERNAME}
      password: ${DOCKER_PASSWORD}
      dry_run: true
      pull: false
      platform:
        - linux/arm/v7
        - linux/arm64
        - linux/amd64
      labels:
        - org.opencontainers.image.revision=${PCIT_COMMIT}
        - org.opencontainers.image.source=https://github.com/${PCIT_REPO_SLUG}
      no_cache: false
      cache_from:
        - pict/alpine:cache
      cache_to:
        - type=local%2Cdest=/tmp/build-cache
      secret:
        - id=mysecret%2Csrc=secret.txt
      output:
        # - .
        # - path
        # - type=local%2Cdest=path
        # - type=tar%2Cdest=path
        # - type=oci%2Cdest=path
        # - type=docker%2Cdest=path%2Ccontext=my-context
        # - type=image%2Cname=name%2Cpush=false
        - type=image%2Cpush=true
        # - type=registry
      buildx_image: dockerpracticesig/buildkit:master
    if:
      event: push
      branch: master
      # event: tag

  docker_build_repo_array:
    image: pcit/docker
    with:
      registry: ccr.ccs.tencentyun.com
      repo:
        - pcit/alpine
        - pcit/alpine:v2
      # target: php
      build_args:
        - a=1
        - b=2
      context: ./tests
      dockerfile: tests/Dockerfile
      # dockerfile: path/to/Dockerfile
      username: ${TENCENT_DOCKER_USERNAME}
      password: ${DOCKER_PASSWORD}
      dry_run: false
      pull: false
      platform:
        - linux/arm/v7
        - linux/arm64
        - linux/amd64
      labels:
        - org.opencontainers.image.revision=${PCIT_COMMIT}
        - org.opencontainers.image.source=https://github.com/${PCIT_REPO_SLUG}
      no_cache: false
      buildx_image: dockerpracticesig/buildkit:master
    if:
      event: push
      branch: master
      # event: tag

  docker_build_dont_push:
    image: pcit/docker
    with:
      # registry: docker.khs1994.com
      repo: pcit/alpine
      # target: php
      build_args:
        - a=4
        - b=5
      context: ./tests
      dockerfile: tests/Dockerfile
      # dockerfile: path/to/Dockerfile
      username: ${DOCKER_USERNAME}
      password: ${DOCKER_PASSWORD}
      dry_run: true
      buildx_image: dockerpracticesig/buildkit:master
    if:
      event: push
      # event: tag
      branch: master

  exec_command:
    image: pcit/docker
    run: |
      docker buildx create --name pcit-builder \
        --driver docker-container --use \
        --driver-opt image=dockerpracticesig/buildkit:master

      docker buildx build -f tests/Dockerfile tests
      docker buildx build -t test -f tests/Dockerfile tests

      docker buildx rm pcit-builder
